name: Run tests on the server
on: [push]

jobs:
  test_server:
    name: Server tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3


      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: '4.4' 

      - name: Create config file
        env: 
          CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: echo "module.exports = {
            databaseUri:"mongodb://localhost:27017/meetio",
            secret:"my_secret_key",
            defaultAvatarFile:{
                url:"https://res.cloudinary.com/dwu5a3e7e/image/upload/v1672860673/meetio/avatars/avatar-1672856932301-lW9SALQB9i_uammqt.png",
                public_id:"avatar-1672856932301-lW9SALQB9i_uammqt"
            },
            cloudinaryConfig:{
                cloud_name:${env.CLOUD_NAME},
                api_key:${env.API_KEY},
                api_secret:${env.API_SECRET},
                secure:true
            }}">server/config.js
      - name: Install client dependencies
        run: cd server/src/client/ && npm i

      - name: Build client
        run: cd server/src/client/ && npm run build

      - name: Create pictures/ folder
        run: cd server/src/client/build/ && mkdir pictures

      - name: Install server dependencies
        run: cd server/ && npm i

      - name: Run tests
        run: cd server/ && npm test
