name: test server
on: [push, pull_request]
jobs:
  test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: ls
      - run: touch server/src/config.js
