name: Run tests on the server
on: [push]

jobs:
    test_server:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v3


            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Start MongoDB
              uses: supercharge/mongodb-github-action@1.6.0
              with:
                  mongodb-version: '4.4' 

            - name: Create config file
              env:
                DATABASE_URI: ${{ secrets.DATABASE_URI }}
                CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
                CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
                CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
                SECRET: ${{ secrets.SECRET }}
              run: |
                cat > .env << EOF
                DATABASE_URI='$DATABASE_URI'
                CLOUDINARY_API_KEY='$CLOUDINARY_API_KEY'
                CLOUDINARY_API_SECRET='$CLOUDINARY_API_SECRET'
                CLOUDINARY_CLOUD_NAME='$CLOUDINARY_CLOUD_NAME'
                DEFAULT_AVATAR_FILE_PUBLIC_ID='avatar.png'
                DEFAULT_AVATAR_FILE_URL='https://res.cloudinary.com/dwu5a3e7e/image/upload/v1697032147/meetio/avatars/avatar.png'
                SECRET='$SECRET'
                EOF
            - name: Install client dependencies
              run: cd server/src/client/ && npm i

            - name: Build client
              run: cd server/src/client/ && npm run build

            - name: Create pictures/ folder
              run: cd server/src/client/build/ && mkdir pictures

            - name: Install server dependencies
              run: cd server/ && npm i

            - name: Run tests
              run: cd server/ && npm test
